# Generated by Django 4.1.2 on 2022-11-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_user_auth0_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth0_id',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
