# Generated by Django 4.1.2 on 2022-11-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
