# Generated by Django 4.1.2 on 2022-11-20 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_business_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='report',
            name='business_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.business', verbose_name='BusinessID'),
        ),
    ]
